### ISSUE TITLE
Best Segment Time incorrect when inserting splits via Editor

### ISSUE THREAD

**Issue by hallcristobal** [CryZe/livesplit-core#63] opened 2017-07-14 15:45 UTC
![screenshot_661](https://user-images.githubusercontent.com/12072058/28219389-cf77e3cc-6889-11e7-977f-313e59279eb5.png)
[Both LSS files Side By Side](https://www.diffchecker.com/8v6r6bKf)

**Comment by CryZe** [comment] 2017-07-14 16:26
This may be a duplicate of #20

**Comment by CryZe** [comment] 2017-07-14 16:26
Lmao, GitHub pls

**Comment by CryZe** [comment] 2017-07-20 13:48
Okay, so this seems to be what #22 is talking about. The fixing algorithm happens while typing, so the Best Segment is getting set way too early.

**Comment by CryZe** [comment] 2017-07-20 14:05
I just pushed a Unit Test that shows that this is just a LiveSplit One bug: 

https://github.com/CryZe/livesplit-core/blob/8d5d277b85d81600f0d2c47c8295388bb3cf21eb/src/run_editor/tests.rs#L5

**Comment by hallcristobal** [comment] 2017-11-05 19:19
Not sure why I closed this, is definitely still a bug with LiveSplit One

**Comment by CryZe** [comment] 2017-11-05 20:29
That's because it's not a bug in livesplit-core.

**Comment by hallcristobal** [comment] 2018-01-25 16:56
Should be closed?

**Comment by wooferzfg** [comment] 2018-01-25 17:01
yes

**Closed** 2018-01-25 17:03 UTC
Labels: bug
